name: Build SDL2-Android

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger when creating a PR to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to run the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev cmake clang wget unzip zip

      - name: Download and setup Android NDK
        run: |
          # Create a folder for the NDK
          mkdir -p /home/runner/ndk
          
          # Download the NDK (r21d is an example, change if needed)
          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip -O /home/runner/ndk/ndk.zip
          
          # Unzip the NDK into the folder
          unzip /home/runner/ndk/ndk.zip -d /home/runner/ndk
          
          # Clean up the zip file
          rm /home/runner/ndk/ndk.zip

      - name: Set environment variables
        run: |
          echo "NDK_PATH=/home/runner/ndk/android-ndk-r21d" >> $GITHUB_ENV
          echo "BUILD_PREFIX=/home/runner/build" >> $GITHUB_ENV

      - name: Run build.sh with options (suppress excessive output)
        id: build_output
        run: |
          chmod +x ./build.sh
          # Suppress excessive output and only capture errors to the log
          ./build.sh --prefix=$BUILD_PREFIX --ndkdir=$NDK_PATH --arch=armeabi-v7a --api=16 > build_output.log 2>&1

      - name: Check build output
        run: |
          echo "Build completed. Listing build directory contents..."
          ls -al /home/runner/build  # List all files in the build directory for debugging

      - name: Upload build output folder
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-output-folder
          path: /home/runner/build/lib  # Directly upload the 'lib' folder

      - name: Upload build output log
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-output-log
          path: build_output.log  # Upload the captured log file as an artifact
