name: Build SDL2-Android

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger when creating a PR to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to run the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev cmake clang wget unzip zip

      - name: Download and setup Android NDK
        run: |
          # Create a folder for the NDK
          mkdir -p /home/runner/ndk
          
          # Download the NDK (r21d is an example, change if needed)
          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip -O /home/runner/ndk/ndk.zip
          
          # Unzip the NDK into the folder
          unzip /home/runner/ndk/ndk.zip -d /home/runner/ndk
          
          # Clean up the zip file
          rm /home/runner/ndk/ndk.zip

      - name: Set environment variables
        run: |
          echo "NDK_PATH=/home/runner/ndk/android-ndk-r21d" >> $GITHUB_ENV
          echo "BUILD_PREFIX=/home/runner/build" >> $GITHUB_ENV

      - name: Run build.sh with options (Suppress excessive output)
        id: build_output
        run: |
          chmod +x ./build.sh
          ./build.sh --prefix=$BUILD_PREFIX --ndkdir=$NDK_PATH --arch=armeabi-v7a --api=16 > build_output.log 2>&1

      - name: Check if required directories exist
        run: |
          echo "Checking if directories exist..."
          ls /home/runner/build/libs
          ls /home/runner/build/obj/libs/arm64-v8a

      - name: Zip the build output (with checks)
        run: |
          # Check if the directories exist and zip if they do
          if [ -d "/home/runner/build/libs" ] && [ -d "/home/runner/build/obj/libs/arm64-v8a" ]; then
            zip -r /home/runner/build_output.zip /home/runner/build/libs /home/runner/build/obj/libs/arm64-v8a
          else
            echo "Required directories not found. Skipping zipping."
          fi

      - name: Upload build output zip
        uses: actions/upload-artifact@v3
        with:
          name: build-output-zip
          path: /home/runner/build_output.zip  # Upload the zip file containing build output

      - name: Upload build output log (Limited verbosity)
        uses: actions/upload-artifact@v3
        with:
          name: build-output-log
          path: build_output.log  # Upload the captured log file as an artifact
